apiVersion: v1
kind: Service
metadata:
  name: web-service
spec:
  type: NodePort   # or LoadBalancer if supported
  selector:
    app: docker-k8s-lab
  ports:
    - port: 80
      targetPort: 3000
      nodePort: 30030
